behavior:
  headless: false
  useChrome: false
  keepAlive: false
viewport:
  width: 1024
  height: 1024 
network:
  block:
    - "*.googletagmanager.com/*"
    - "*.google-analytics.com/*"
retry:
  enabled: true
  maxRetries: 3
  retryDelay: 5000
llm:
  cache:
    enabled: true
    path: "llm_cache"
claude:
  apiKey: "your-api-key-here"
  model: "claude-3-5-sonnet-20241022"
  temperature: 0.7
  maxTokens: 1024
  topP: 1
  topK: 1
  frequencyPenalty: 0
  presencePenalty: 0